header:
  license:
    spdx-id: AGPL-3.0-or-later
    copyright-owner: Genome Research Ltd
    content: |
      Copyright (c) 2021 Genome Research Ltd.

      Author: Cancer Genome Project <cgphelp@sanger.ac.uk>

      This file is part of NanoSeq.

      NanoSeq is free software: you can redistribute it and/or modify it under
      the terms of the GNU Affero General Public License as published by the Free
      Software Foundation; either version 3 of the License, or (at your option) any
      later version.

      This program is distributed in the hope that it will be useful, but WITHOUT
      ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
      FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
      details.

      You should have received a copy of the GNU Affero General Public License
      along with this program. If not, see <http://www.gnu.org/licenses/>.

    pattern: |
      Copyright \(c\) [\-0-9]+ Genome Research Ltd

      Author: .+

      This file is part of NanoSeq.

      NanoSeq is free software: you can redistribute it and/or modify it under
      the terms of the GNU Affero General Public License as published by the Free
      Software Foundation; either version 3 of the License, or (at your option) any
      later version.

      This program is distributed in the hope that it will be useful, but WITHOUT
      ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
      FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
      details.

  paths:
    - '**'

  paths-ignore:
    - '.circleci'
    - '.dockerignore'
    - '.gitignore'
    - 'CHANGES.md'
    - 'Dockerfile'
    - 'LICENSE'
    - 'Makefile'
    - 'README.md'
    - 'EXAMPLE'
    - '**/*.yaml'
    - 'src/bamcov.c'
    - 'src/sam_opts.*'
    - 'src/samtools.*'
    - 'src/sam_utils.*'
    - 'test/*'
    - 'LSF/*'

  comment: on-failure
